[package]
name = "d17"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.7"
nom = "7.1.3"

[dev-dependencies]
rstest = "0.18.2"
